name: Godot Builder Itchio

on:
#  workflow_dispatch:
   push:
     branches:
       - main

jobs:         
 buildWebGL:
   name: Build for WebGL 🖥️
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
       
     #- name: Set Talo API Key
     #  run: |
     #    sed -i "s|access_key=.*|access_key=\"$TALO_API_KEY\"|" addons/talo/settings.cfg
     #  env:
     #    TALO_API_KEY: ${{ secrets.TALO_API_KEY }}

     - name: Godot Export
       uses: firebelley/godot-export@v6.0.0
       with:
         godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
         godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
         relative_project_path: ./
         use_preset_export_path: true
         verbose: true
         
     - uses: actions/upload-artifact@v3
       with:
         name: build-WebGL
         path: build/WebGL
         
 deployPages:
   needs: buildWebGL
   name: Deploy to Itch.io 🚀
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - uses: actions/download-artifact@v3
       with:
         name: build-WebGL
         path: build/WebGL

     - name: Display structure of root files
       run: ls -R
       working-directory: build/WebGL

     - name: Deploy 🚀
       uses: JamesIves/github-pages-deploy-action@4.1.4
       with:
         branch: itch-io
         folder: build/WebGL
         
     - uses: yeslayla/butler-publish-itchio-action@master
       env:
         BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
         CHANNEL: HTML
         ITCH_GAME: life-is-bubblance
         ITCH_USER: davidlms
         BRANCH: itch-io
         PACKAGE: build/WebGL
